#CRUD
vitrine_client:
    resource: "@VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /client
vitrine_article:
    resource: "@VitrineBundle/Resources/config/routing/article.yml"
    prefix:   /article
vitrine_categorie:
    resource: "@VitrineBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie
vitrine_commande:
    resource: "@VitrineBundle/Resources/config/routing/commande.yml"
    prefix:   /commande


#pages statiques de base
vitrine_homepage:
    path:     /accueil/{name}
    defaults: { _controller: VitrineBundle:Default:index, name: visiteur }
mentions:
    path:     /mentions
    defaults: { _controller: VitrineBundle:Default:mentions}

#front sans connexion
catalogue:
    path:     /catalogue
    defaults: { _controller: VitrineBundle:Article:index}
promotions:
    path:     /catalogue
    defaults: { _controller: VitrineBundle:Article:promotions}
articles_par_categorie:
    path:     /catalogue/{id_categorie_article}
    defaults: { _controller: VitrineBundle:Categorie:index }

    
#/connexion/deconnexion/incription 
connexion:
    path:     /connexion
    defaults: { _controller: VitrineBundle:Session:connexion }

deconnexion:
    path:     /deconnexion
    defaults: { _controller: VitrineBundle:Session:deconnexion }

#front une fois connecté
panier:
    path:     /panier
    defaults: { _controller: VitrineBundle:Panier:index}
panierContenu:
    path:     /panier/contenuPanier
    defaults: { _controller: VitrineBundle:Panier:contenuPanier}
ajoutArticlePanier:
    path:     /panier/ajoutArticlePanier
    defaults: { _controller: VitrineBundle:Panier:ajoutArticlePanier}
suppressionArticlePanier:
    path:     /panier/suppressionArticlePanier/{id_article}
    defaults: { _controller: VitrineBundle:Panier:suppressionArticlePanier}
viderPanier:
    path:     /panier/viderPanier
    defaults: { _controller: VitrineBundle:Panier:viderPanier}
confirmationPanier:
    path:     /panier/confirmationPanier
    defaults: { _controller: VitrineBundle:Panier:confirmationPanier}
    
#...
