services:
#    vitrine.example:
#        class: sil14\VitrineBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     #VitrineBundle:
        #class: Categorie
        #arguments: [@doctrine.orm.entity_manager]