# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        sil16\VitrineBundle\Entity\Client:
            algorithm: bcrypt
            cost: 12
    role_hierarchy:
         ROLE_ADMIN: ROLE_CLIENT

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        utilisateurs:
            entity: { class: VitrineBundle:Client, property: email }

    firewalls:
        vitrine_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_denied_url: /refus
    access_control:
        # A REMETTRE QUAND LA CLASSE ADMIN SERA TERMINEE, en attendant les user connectés peuvent gérer le back office
        #- { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/client, roles: ROLE_CUSTOMER }
