sil14\VitrineBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nom:
            type: string
            length: 100
        mail:
            type: string
            length: 100
        password:
            type: string
            length: 30
