sil14\VitrineBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nom:
            type: string
            length: 100
        mail:
            type: string
            length: 100
    oneToMany: 
        commandes:
            targetEntity: Commande
            mappedBy: client
