sil14\VitrineBundle\Entity\LigneCommande:
    type: entity
    table: ligneCommande
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        prix:
            type: decimal
            scale: 2
        quantite:
            type: integer
    manyToOne:
        article:
            targetEntity: Article
            inversedBy: attributes
            joinColumn:
              libelle: article_id
              referencedColumnName: id
        commande:
            targetEntity: Commande
            inversedBy: attributes
            joinColum:
              libelle: commande_id
              referencedColumnName: id