article_index:
    path:     /list
    defaults: { _controller: "VitrineBundle:Article:list" }
    methods:  GET

article_show:
    path:     /{id}/show
    defaults: { _controller: "VitrineBundle:Article:show" }
    methods:  GET

article_new:
    path:     /admin/new
    defaults: { _controller: "VitrineBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "VitrineBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "VitrineBundle:Article:delete" }
    methods:  DELETE
