client_index:
    path:     /
    defaults: { _controller: "VitrineBundle:Client:index" }
    methods:  GET

client_show:
    path:     /{id}/show
    defaults: { _controller: "VitrineBundle:Client:show" }
    methods:  GET

#client_new:
    #path:     /new
    #defaults: { _controller: "VitrineBundle:Client:new" }
    #methods:  [GET, POST]

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "VitrineBundle:Client:edit" }
    methods:  [GET, POST]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "VitrineBundle:Client:delete" }
    methods:  DELETE
